### ISSUE TITLE
`A timeout was reached` error

### ISSUE THREAD

**Issue by megatolya** [logux/logux#101]
In my team's project we get many 'timeout was reached' errors from logux. We suppose it happens when the server restarts.

This timeout is managed in the Logux BaseNode: https://github.com/logux/core/blob/main/base-node/index.js#L247

...and it is started when another node connects to the server, see Logux ServerNode here: https://github.com/logux/core/blob/main/server-node/index.js#L26

I'm not sure how to investigate such error. And what exact nature of it. If you have any suggestions or recommendations on that, that would be very helpful.

![image](https://user-images.githubusercontent.com/2204267/151825422-fb85774a-2ad0-44e5-abb1-08427bfabdcd.png)

**Comment by ai** [comment]
The first theory:

Browsers reduce timer scale in background tabs. For instance, `setTimeout` with `every second` will run only every 20 seconds.

Maybe this background tab timer economy mode affect Logux timer.

How to test this theory:

1. Do you have this error in every browser? Or in some specific browser?
2. Can you increase `timeout` option in `Server` options and see, will it solve the problem?

**Comment by mifopen** [comment]
@ai I've just proven your theory :)
Here are logs from an abandoned tab with setInterval(..., 3000)
![Screen Shot 2022-02-19 at 2 04 41 PM](https://user-images.githubusercontent.com/19679857/154806335-641fb738-81ee-4c48-ae5e-c9e61fabd3d8.png)
You can notice throttling before and after the error. (The real timeout is 20sec not 6ms, the message was patched by me in source codes, nm)
And the exact reason is https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

**Comment by ai** [comment]
> once per minute

Got it. I will update default timer.

You can solve the issue quicker by changing timeout manually.

**Comment by mifopen** [comment]
Yeah, already. Also, do we understand right, that we can't avoid this error message for all connected nodes in case of an ungracefully broken connection? And that's why you have this one https://github.com/logux/logux/issues/100?

**Comment by ai** [comment]
> We can't avoid this error message for all connected nodes in case of an ungracefully broken connection

Yes. It should be threaded as warning (maybe we can change something to improve log integration) not as error.

DevOps engineer need to maintain the statistics of this warning. The single warning is not a problem, but some non-standard waves could tell about some issues in the system.

**Comment by ai** [comment]
> And that's why you have this one https://github.com/logux/logux/issues/100?

This issue is for the case when we have long task in JS which block thread for sending `ping`.

**Comment by ai** [comment]
Fixed https://github.com/logux/core/commit/0f8ee8edb112749c6a586040695df7f538b5b59b

**Comment by ai** [comment]
The fix was released in Logux Core 0.7.3.

**Comment by erictheswift** [comment]
Hey!
https://github.com/logux/server/blob/51c62dd523477187a8c45324d22f3c67dd871ce2/base-server/index.js#L144
https://github.com/logux/server/blob/7279997a2f714348dcd3a58db61b225ee228fd38/base-server/index.d.ts#L113
Shouldn't these constants also be updated?

**Comment by ai** [comment]
Server's timeout = 2 × client's ping.

It looks like correct. Maybe I am missing something?

**Comment by erictheswift** [comment]
But this discussion figured out that client node may awake as rare as once per minute and

that's why this default was updated by you https://github.com/logux/core/commit/0f8ee8edb112749c6a586040695df7f538b5b59b#diff-dbbcf8237396deeb3580dcd77ad379d80477c54d7fd49c503b80c10f08b8c214R5

Still in runtime ServerNode.DEFAULT_OPTIONS.timeout (70000) gets overridden by BaseServer options.timeout (20000) — I'm also wondering if I'm wrong somewhere.

Now I still have lots of "A timeout was reached (20000ms)" in my setup with default options.

**Comment by erictheswift** [comment]
As I see, DEFAULT_OPTIONS are not accounted neither by ClientNode nor by ServerNode because they are always defaulted and provided from outside (BaseServer, Client).

**Comment by erictheswift** [comment]
BaseServer
```
   if (this.options.time) {
      log = this.options.time.nextLog({ store, nodeId: this.nodeId })
    } else {
      log = new Log({ store, nodeId: this.nodeId })
      if (typeof this.options.timeout === 'undefined') {
        this.options.timeout = 20000
      }
      if (typeof this.options.ping === 'undefined') {
        this.options.ping = 10000
      }
    }
```

Client
```
    if (!this.options.time) {
      if (typeof this.options.timeout === 'undefined') {
        this.options.timeout = 20000
      }
      if (typeof this.options.ping === 'undefined') {
        this.options.ping = 5000
      }
    }
```

**Comment by erictheswift** [comment]
That makes this https://github.com/logux/core/commit/0f8ee8edb112749c6a586040695df7f538b5b59b fix to have zero effect for real, non-test setup

**Comment by erictheswift** [comment]
Also check d.ts type definitions — they had old default values inlined as a field descriptionRegards,NikitaOn 24 Apr 2023, at 18:48, Andrey Sitnik ***@***.***> wrote:﻿
Yes, you are right. Good catch. Fixed:
***@***.***
***@***.***
I will release after migration from Jest and to Nano Stores 0.8.

**Comment by ai** [comment]
Thanks. I fixed it too.
