### ISSUE TITLE
Subscriptions are kept alive when initiated offline

### ISSUE THREAD

**Issue by DaDom** [logux/logux#103]
Hi!

We are using Logux in combination with Redux + React, i.e. we have components that contain something like:

```typescript
const isSubscribing = useSubscription([channel]);
```

`channel` is a prop which changes based on user navigation. Every time `channel` has a new value, the subscription for the previous channel is correctly unsubscribed, and a new subscription for the new channel is established.

This all works fine, but we observed a strange behaviour when this happens while the user is offline.
Imagine we have channels `A`, `B` and `C`, and the following happens:

1. The user goes offline
2. The user navigates so that `channel === 'A'`
3. The user navigates further so that `channel === 'B'`
4. The user navigates further so that `channel === 'C'`
5. The user goes online

My expectation is that now the user has an active subscription for channel `C`, while the already outdated subscriptions for channel `A` and `B` are terminated.
We however see the following:

- After the users navigation in offline mode, the logux clients attempts to establish a new subscription to all three channels; the client node is in state `sending`
- As soon as the user goes online, the logux client logs that `logux/unsubscribe` has been processed for channel `A` and `B` - looks fine, but...
- Shortly after that, the logux client logs `Logux subscribing to channel ...` for all three channels, and ultimately `Logux subscribed to ... channel` for all three channels, and not necessarily in order `A, B, C`
- Also, the actions returned by the `accessAndLoad` callback on server-side is delivered and processed for all three channels, which is not desired as well - at least not out of subscription order.

We now have three active subscriptions in parallel, i.e. the client receives updates for all of them, which is certainly not desired.
Do we have to add some checks to prevent this?

Any hint is appreciated, thank you!

**Comment by ai** [comment]
Yes, we have no optimization of removing subscription action from log, when we do not need it anymore.

I will think how to clean log from outdated channels.

**Comment by DaDom** [comment]
Great, thanks a lot, looking forward to your thoughts 👍

**Comment by DaDom** [comment]
Hi @ai !

Any news on this issue?

Thanks a lot!

**Comment by ai** [comment]
Sorry, didn’t have a time. Too many works.

**Comment by ai** [comment]
Thanks for the waiting.

I pushed the fix 3609ae8

Can you try to check in from `next` branch of `@logux/client` (just re-install dependency directly from GitHub by `yarn add @logux/client@logux/client#next`)?

**Comment by DaDom** [comment]
Awesome! Will check it out over the weekend, thank you

**Comment by DaDom** [comment]
Thank you @ai and sorry for the delay.
Tested it with freshly released logux-client 0.17.0 and works great!
