### ISSUE TITLE
Logux Data API

### ISSUE THREAD

**Issue by ai** [logux/logux#11]
We need a built-in model-based API. Something like GraphQL, but with CRDT.

This issue only about creating an API.

There will be more issues with part of implementations.

**Comment by uhbif19** [comment]
@ai You have closed client#20 in favor of this issue. But I do not see any mentions of GraphQL here. Is this correct?

**Comment by ai** [comment]
> But I do not see any mentions of GraphQL here. Is this correct?

“Something like GraphQL, but with CRDT”

Logux Data will load the graph of the modules from the server.

**Comment by uhbif19** [comment]
@ai Idea of "Logux—GraphQL proxy server" [suggested](https://github.com/logux/client/issues/20#issuecomment-300185539) in closed issue, would cover cases of connection Logux client apps with GraphQL backend-less solutions, like Hasura.

As far as I understand "Something like GraphQL" will not help with such task.

**Comment by ai** [comment]
I do not plan GraphQL compatible API.

Technically, it can be made on top of Logux Data for request only (without mutations support, because it is impossible to make collaborative editor on top of mutation architecture). But I do not want to have too many open issues with ideas.

We can think about the GraphQL reading bridge when Logux Data will be ready. Right now I am not sure that it will be 100% possible (since I am still not sure about the Logux Data architecture and API).

**Comment by uhbif19** [comment]
> because it is impossible to make collaborative editor on top of mutation architecture

Why so? Cannot proxy-backend just translate actions to mutations?

**Comment by ai** [comment]
We can, but I am not sure that we should.

Logux actions have extra data to allow collaboration and offline. On action to mutation conversation we will lose this extra data and collaboration/offline support. Very likely that real-time will be lost as well.

I am not sure that there is a reason to use Logux without all Logux features.

**Comment by uhbif19** [comment]
> We can, but I am not sure that we should.

Sure. I am just trying to understand how this thing works, and what are limits to its integration. I surely 

> Logux actions have extra data to allow collaboration and offline.

Sorry, I am surely missing something. Cannot this meta-infomation be processed by our proxy, and GraphQL used just like passive DB without Logux metadata?

I thought that this is just how `logux-django` (and other servers) are working. 

Taking example from README:

```
class RenameUserAction(ActionCommand):
        ...

        def process(self, action: Action, meta: Optional[Meta]) -> None:
            user = User.objects.get(pk=action['user'])
            user.first_name = action['name']
            user.save()
```
As far, as I understand, this processing code throws out the Logux metadata and saves data to DB. Could not we just send User-changing mutation in hypothetical to-GraphQL proxy?

**Comment by ai** [comment]
> Sorry, I am surely missing something. Cannot this meta-information be processed by our proxy, and GraphQL used just like passive DB without Logux metadata?

Logux Back-end Protocol (`logux-django`) sends actions to the back-end. Mutations can’t be mapped 1-by-1 to actions. So it will not work out of the box. You will need some sort of convertor.

It is solvable, but it is too early to speak about it before we don’t have Logux Data.

**Comment by uhbif19** [comment]
> You will need some sort of convertor.

Yes, sure, you right.

> It is solvable, but it is too early to speak about it before we don’t have Logux Data.

Okay, now I understand your position. Thank you.

**Comment by cosminv6u** [comment]
Can I help with something? I know Js + Ts very good and I could write code for logux.

We use Logux in our app and we really need the CRDT part, that was the main reason to pick Logux in the first place.
Can you quickly tell in a message what needs to be done for CRDT, to have a starting point at least.

I had a look at 2 alternatives: https://github.com/automerge/automerge and https://github.com/gritzko/swarm but didn't tried them out.

**Comment by ai** [comment]
@cosminv6u very soon I will publish API proposal and I will need a good review from the community

**Comment by ai** [comment]
Here is the API proposal: https://gist.github.com/ai/dfea0fcbfe8fba1b1e11180a1e5d16e3

Does it fit your needs? Do you miss something from GraphQL?

**Comment by cosminv6u** [comment]
Well I looked at the code, I understood some parts, some not. I'm more familiar with Angular and Vue, not with React (though there shouldn't be too many differences).

Also I'm not an expert in CRDT, I understand the concept, but to understand the low level implementation details I kept looking at this video https://www.serverless.com/blog/crdt-explained-supercharge-serverless-at-edge and I'm trying to write down how CRDT will behave for all our usecases, which requires higher level thinking. Then I'm going to think how I could use your Logux Data implementation proposal for all our usecases.

It would be nice if you can provide more details (written, not only code) about how things will be implemented under the hood, if CRDT will be 100% implemented or only partially. Things like: timestamp & uuid per field, per object, Delta Vector Clock? Causal Consistency, etc. This way maybe we will also understand better how CRDT works. 10x!

**Comment by ai** [comment]
> Things like: timestamp & uuid per field, per object, Delta Vector Clock

1. We already have distributed clock https://logux.io/guide/concepts/meta/#id-and-time
2. For each Map we will store the last changes distributed time for each key

> if CRDT will be 100% implemented

I plan to start with `Map` implementation (key-value object with last-write-wins per each key). Then we plan to implement `Vector` (like an Array in CRDT, where multiple users can add/remove keys at the same moment without overriding each other) and `Set`. In the end we will implemenent `Text`.

In my understandard, CRDT is a philosphy rather than some specification to be “fully implemnteted”. There are few core ideas (distributed time, all nodes are equal, the state is the same on all nodes after syncing). But there are many different types in CRDT: for instance, a few `Text` implementation was created. There are even two very different implemntation approaches: state-based and log-based (most of modern implementations are in the middle including Logux).

> This way maybe we will also understand better how CRDT works

I am afraid to spend too much time writing docs before having the actual code. This gist is about API to check that our API will fit all use cases.

When implementation will be ready, I defintally will add guides and recipes to [`logux.io`](https://logux.io/). But I can do it propertly only when I will have implementation since many things can be changed during the development.

**Comment by ai** [comment]
I started Logux State https://github.com/logux/state

Each CRDT model will have a separate issue. This issue can be closed/
