### ISSUE TITLE
Problem calling changeUser

### ISSUE THREAD

**Issue by zumkorn** [logux/logux#15]
When use `client.changeUser()`, get error:

```
Logux state is connecting index.js:37
Logux tab role is leader index.js:37
Logux state is synchronized. Client was connected to server:cENrd9FY. index.js:37
Logux state is disconnected index.js:37
Logux state is connecting index.js:37
Logux state is disconnected index.js:37
Logux error: undefined index.js:1
    e index.js:1
    showError index.js:43
    log index.js:75
    emit index.js:5
    error index.js:212
    BaseNode index.js:93
    emit index.js:5
    send index.js:73
    send index.js:112
    send index.js:143
    sendConnect index.js:84
    initializing index.js:19
Logux error: undefined index.js:1
    e index.js:1
    showError index.js:43
    log index.js:75
    emit index.js:5
    error index.js:212
    send index.js:145
    sendConnect index.js:84
    initializing index.js:19
Firefox can't establish a connection to the server at ws://localhost:31337/. index.js:46
Error: WS was closed index.js:73
The connection to ws://localhost:31337/ was interrupted while the page was loading. index.js:46
Logux error: undefined index.js:1
    e index.js:1
    showError index.js:43
    log index.js:75
    emit index.js:5
    error index.js:212
    BaseNode index.js:93
    emit index.js:5
    onerror index.js:20
Error: WS Error index.js:20
    onerror index.js:20
```

I create simple app(React,  Logux Redux) with one button, that call `client.changeUser(clientId, token)`. Logux is used as a server.
Repository with example: https://github.com/zumkorn/logux-simple-app

**Comment by ai** [comment]
Fixed by https://github.com/logux/core/commit/809c59ebbfb3857576eb4af5b4c2461d046261a7 and https://github.com/logux/client/commit/3b6ebfcc1bff5acf29edec7735b86ea1158ba9fe

I will keep this issue open since I want to also refactor `Client#changeUser` code.

**Comment by ai** [comment]
Done https://github.com/logux/client/commit/3b461367f3d553ddcaf166361138d1daa30fe2ff

**Comment by zumkorn** [comment]
I have tried this.
But now an error appears:

> Without SSL, old proxies block WebSockets. Use WSS for Logux or set allowDangerousProtocol option.

Now the environment(prod/dev) is determined by headers? Who i can set them?

**Comment by ai** [comment]
@zumkorn update `@logux/server` in your server too

**Comment by zumkorn** [comment]
Yes, I also updated the server. But that didn’t help.
There may be a problem in the macOS Catalina.
I will try to find the problem.

Repo updated: https://github.com/zumkorn/logux-simple-app

**Comment by ai** [comment]
Hm, maybe I made a mistake in headers environment detection

**Comment by ai** [comment]
Thanks for the report. Fixed https://github.com/logux/client/commit/d66b115bb1c53c05629edb5a4088734e0fa43593
