### ISSUE TITLE
Add CrossTabClient#waitFor

### ISSUE THREAD

**Issue by clibu** [logux/logux#21]
I'm seeing weirdness in MS Edge Version 81.0.416.68 (Official build) (64-bit) and on Firefox 75.0 (64-bit) with CrossTabClient ```connected=false``` and ```state="disconnected"``` when I refresh the Browser and receive ```"logux/subscribe"```. 

Chrome is fine with ```connected=true``` and ```state="synchronized"```. Just thought I'd mention it in case there is an underlying Logux issue.

In fact on Chrome I see ```connected=true``` and ```state="synchronized"``` straight after calling 
```
client.start(); 
client.log.add( { type: 'logux/subscribe', channel: 'xyz' }, { sync: true } )
// connected=true state="synchronized" on Chrome.
// connected=false state="disconnected" on Edge and FF.
```
All Browsers are up to date. Using Win 10 and a simple Logux Server running on Node v10. I've rebooted the PC and get same results.

**Comment by ai** [comment]
It could happen because you do not wait until the connection will be established. There are many reasons why the exact value of `state` will be different just after `start()` call.

Can you try to add `client.node.waitFor` before checking the value?

```js
client.start(); 
client.log.add( { type: 'logux/subscribe', channel: 'xyz' }, { sync: true } )
client.node.waitFor('synchronized', () => {
  console.log(client.connected, client.state)
})
``

**Comment by clibu** [comment]
@ai Ok, it looks like my original comment was wrong. On both Chrome and Edge I now see: ```state: disconnected, connected: false``` I think my original post was a logging issue on my part.

I've tried using ```waitFor()``` as below and I never see the callback called.
````
    serverSubscribe(){
        // ref: https://logux.io/guide/concepts/subscription/
        this.syncClient.log.add( { type: 'logux/subscribe', channel: 'notes' }, { sync: true } )
        mlog.info( '1) syncClient state:', this.syncClient.state, 'connected:', this.syncClient.connected )   // 1) state: disconnected, connected: false

        this.syncClient.node.waitFor( 'synchronized', () => {
            mlog.info( '2) this.waitFor syncClient:', this.syncClient )     // never seen
        })
    }
````
Aplogogies for the late reply.

**Comment by ai** [comment]
@clibu `this.syncClient.node.waitFor` returns `Promise` and do not accept callback. You need to use it like this:

```js
this.syncClient.node.waitFor( 'synchronized' ).then( () => {
  mlog.info( '2) this.waitFor syncClient:', this.syncClient )
})
```

**Comment by clibu** [comment]
@ai Thanks, my bad, I copied your first bit of code as is. Promise works, however only the ```leader``` tab sees it resolved, which maybe by design?

**Comment by ai** [comment]
Yeap. Everything with `.node.` works only in local tab.

But it may be a good idea to add `CrossTabClient.waitFor` too.

**Comment by clibu** [comment]
I was confused and didn't think it was working at first. So yes I agree having it work in all Tabs would be useful and avoid confusion.

**Comment by ai** [comment]
I added cross-tab `waitFor` 70b75d5
