### ISSUE TITLE
Vue.js Composition API

### ISSUE THREAD

**Issue by ai** [logux/logux#27]
Vue.js 3 beta is out.

What pattern do they recommend for libraries like ours? Do they recommend hooks?

**Comment by euaaaio** [comment]
Vue team insist that this is called a Composition function or Composition API. It only looks like Hooks.

Also Vue has composition API package for Vue 2 and composition API as core part of Vue 3. It's important not to get confused.

@ai, rename it to "Composition API", please. I don't have access to edit.

**Comment by euaaaio** [comment]
Released in v0.9.0
