### ISSUE TITLE
Add test server for Back-end Protocol

### ISSUE THREAD

**Issue by ai** [logux/logux#31]
We need a test stand to help to develop Logux proxy integrations like Logux Django.

For instance, it can be a preconfigured Logux Client and Logux Server. In the documentation, we explain what behavior is expected from the back-end server (“on the action with this data it should return `denied`”, etc). Logux Client will generate actions and expect some answers from the server.

**Comment by ai** [comment]
What scenarios do we need to test:

1. Wrong token
2. Wrong cookie
3. Back-end throws an error during the auth
4. Unsupported subprotocol (we will implement this feature together with https://github.com/logux/logux/issues/25)
5. Correct token auth
6. Correct cookie auth
7. Access error during the subscription
8. Access error during the action
9. Correct subscription
10. Correct action
11. Wrong secret
12. Wrong message format
13. Unsupported back-end protocol
14. Brute-force attack
15. Sending actions to the clients

@egregors I think we will start from simple unit tests and full integration example we will make later

**Comment by ai** [comment]
The developer of the back-end server should give a back-end with this API:

* Authenticate user with `cookie.token = `${userId}:good`` or `token = `${userId}:good``
* Throw an error on `token = 'error'`
* Supports subprotocols `1.0.x`
* Allow user `10` to subscribe to `user/10`
* Allow user `10` to perform `user/name` action with `userId = 10`
* Server will keep name for each user and change this name only if `user/name` action was created later than the last one
* Default secret is `parole`

I think this server will cover all test cases

**Comment by ai** [comment]
I plan to create a `@logux/backend-test` npm script. The test will look like:

```sh
echo '{ "private": true }' > package.json
yarn add @logux/backend-test@4.0.1 # Back-end protocol version
npx @logux/backend-test localhost:8000 # URL to back-end server
```

**Comment by egregors** [comment]
Awesome! 🔥 🔥 🔥

**Comment by ai** [comment]
The tool was finished
