### ISSUE TITLE
Return actions from channel#load

### ISSUE THREAD

**Issue by ai** [logux/logux#35]
Right now developer must use `await ctx.sendBack` to send the initial state of channel to the client.

It cause two problems:

1. It confuses most of the developers because it is an unusual way
2. forgetting `await` will cause hard-to-find issue of receiving `logux/processed` before the actual data

By allowing to return actions from the `load()` we will fix those issues:

```js
server.channel('foo', {
  …,
  await load() {
    return action // [action1, action2] or [[action1, meta1], action]
  }
})
```

- [x] Add API to the Logux Server https://github.com/logux/server/commit/1101176b6fbb64f59b80b284d39385bce92a7633
- [x] Update docs https://github.com/logux/docs/commit/c0e845ac2ec6766b02c0059bf2237b07ce12f1a8

**Comment by ai** [comment]
@egregors I finally stopped to promote `ctx.sendBack` =^_^=

**Comment by euaaaio** [comment]
Stunning update 🤘🏻

**Comment by egregors** [comment]
> @egregors I finally stopped to promote `ctx.sendBack` =^_^=

Glad to hear that! 👍 👍 👍 

Is that mean, I could exclude `sendBack` from the public API?

**Comment by ai** [comment]
> Is that mean, I could exclude `sendBack` from the public API?

Nope. We still need it to send actions back from `process` callback.

**Comment by egregors** [comment]
> > Is that mean, I could exclude `sendBack` from the public API?
> 
> Nope. We still need it to send actions back from `process` callback.

Maybe `process` should returns `actions` too? ;)

**Comment by ai** [comment]
Both `process`/`load` can contain a few very long steps. It will be nice to have advanced API to send actions before all steps will be finished.

I think we do not need a `return` API from `process` because bwest practice is to send back actions only from channels. Sending back actions during the action processing is a rare thing and having only advanced API will be OK here.
