### ISSUE TITLE
client.changeUser creates 2 ws connections

### ISSUE THREAD

**Issue by droganov** [logux/logux#36]
Hi.
I'm working on auth form and it looks that I've found a bug in `client.changeUser`

In my app, I observe the following picture:

Auth form sends `SignInAction`
```javascript
function handleSubmit(form: Form): void {
    dispatch.sync({ ...form, type: SIGN_IN } as SignInAction);
  }
```

The server handles the action and sends back the credentials:
```javascript
const sessionSignInAction: SessionSignInAction = {
        type: SESSION_CREATE,
        payload: {
          userId,
          token,
          redirectTo: profilePath(),
        },
      };
      ctx.sendBack(sessionSignInAction);
```

Client gets `SESSION_CREATE` event and calls `store.client.changeUser`
```javascript
store.log.on('add', async (action) => {
    switch (action.type) {
      case SESSION_CREATE: {
        const nextCredentials = action.payload;
        saveCredentials(nextCredentials.userId, nextCredentials.token);
        store.client.changeUser(nextCredentials.userId, nextCredentials.token);
        await store.client.node.waitFor('synchronized');
        break;
      }
    }
  });
```

After that logux changed it's state multiple times:

![image](https://user-images.githubusercontent.com/1375299/83300780-4be22400-a201-11ea-9359-d13a4943204f.png)

Initial WS connection was closed, and new connection remained hanging:
![image](https://user-images.githubusercontent.com/1375299/83301570-8d270380-a202-11ea-907d-dabd31c512eb.png)

After that I blurred/focused browser window and another connection was created and the status change log was.

![image](https://user-images.githubusercontent.com/1375299/83301145-ca3ec600-a201-11ea-812a-6bd2434374ff.png)

As a result, I got 2 active WS connections.

Logux client was created with `createLoguxCreator` of `logux-redux` package.

I can sustainably reproduce the case, and the second connection is created on next window event (fucis, location cahnge etc.)

**Comment by droganov** [comment]
Thnx!
I subscribed to https://github.com/logux/logux/issues/15 as well

**Comment by ai** [comment]
Fixed by https://github.com/logux/core/commit/809c59ebbfb3857576eb4af5b4c2461d046261a7 and https://github.com/logux/client/commit/3b6ebfcc1bff5acf29edec7735b86ea1158ba9fe
