### ISSUE TITLE
Allow to write channel#load() actions directly to HTTP answer in Back-end Protocol

### ISSUE THREAD

**Issue by ai** [logux/logux#39]
Right now on subscription, back-end must write `{ answer: "approved", … }` to HTTP response and send HTTP requests with actions of the initial state.

But we can add `{ answer: "action", action, meta }` so back-end will be able to send actions directly in the response.

It will be better for performance and simplify back-end implementations.

@egregors do you agree? I can add these changes to recent Back-End Protocol 4.

**Comment by egregors** [comment]
@ai Sounds good for me. Let's just double-check if I got you correctly. For now, during the bunch of commands processing for subscription action type I `send_back` action (the result of `load` applying) like HTTP request to the Logux server. 
```python
# load
if access_result['answer'] == self.ANSWER.APPROVED:
    try:
        action: Action = self.load(self._action, self._meta)
        self.send_back(action)
        load_result = {
            'answer': self.ANSWER.PROCESSED,
            'id': self._meta.id
        }
[...]
applying_result.append(load_result)
```

You suggest adding load result in the result list before `processed` part of the answer and send it like a part of the bulk response (without `sand_back` execute), right? Smth like:
```python
# load
if access_result['answer'] == self.ANSWER.APPROVED:
    try:
        action: Action = self.load(self._action, self._meta)

        applying_result.extend([
            {
                'answer': self.ANSWER.ACTION,
                **action
            },
            {
                'answer': self.ANSWER.PROCESSED,
                'id': self._meta.id
            }
        ])

    except Exception as load_err:  # pylint: disable=broad-except
        applying_result.append({
            'answer': self.ANSWER.ERROR,
            'id': self._meta.id,
            'details': f'{load_err}'
        })
```

_Don't look at missing `headers` for `load`, this path for subscriptions is not ready yet._

**Comment by ai** [comment]
> You suggest adding load result in the result list before processed part of the answer and send it like a part of the bulk response (without sand_back execute), right?

Yeap. But `self.load` coun return `Action | Action[] | [Action, Meta][]`.

**Comment by ai** [comment]
I added `action` answer to step https://github.com/logux/docs/commit/f6345f2cd7a8b02037b460832f12a04b4cd98595

And add support to Logux Server https://github.com/logux/server/commit/be89fe3077ee60953a8f206b677a95cc8f325fa9

**Comment by egregors** [comment]
> Yeap. But self.load could return Action | Action[] | [Action, Meta][].

So, if `load` returns a few actions I should add to the bulk response the same number of actions? For example, if `load` returns `[[a1, m1], [a1, m2]]` I should add to the response: 
```python
applying_result.extend([
    {
        'answer': self.ANSWER.ACTION,
        **a1,
        **m1
    },
    {
        'answer': self.ANSWER.ACTION,
        **a2,
        **m2
    },
])
```

**Comment by ai** [comment]
Yeap
