### ISSUE TITLE
Simplify  logger/reporter API

### ISSUE THREAD

**Issue by AleksandrSl** [logux/logux#40]
**Problem**: we can pass both custom reporter and logger parameters simultaneously. Logger will be ignored

**Why we can't just remove reporter, though it's low level API**. We need custom reporters for tests. It's not handy to test logger output using snapshots. Therefore, custom reporters are used that write raw reports where we want.

1.(https://github.com/logux/server/pull/97) Replace `reporter` in outer world API with something like `reportComposer`. Thing that converts `event` and `details` into report for `logger`
e.g.
```
type Report = {
  details: object
  level: string
  msg?: string
}

type ReportComposer = <E extends keyof ReportersArguments>(
  event: E,
  payload: ReportersArguments[E]
) => Report | void

let app = createServer({
    ...opts,
    reportComposer (name: string, details: any) {
      names.push(name)
      reports.push([name, details])
    }
})
```
We can pass custom `reportComposer` that will write raw results, and since it returns nothing, nothing will be logged.

Pros:
* Easy to use
* Allows to customize only report generation, built-in loggers can be used.

Cons:
* A little bit disturbing that `reportComposer` can write something, not only return reports.

2. (https://github.com/logux/server/pull/98) Merge `logger`/`reporterStream`/`reporter` into one option
```
export type ReporterOptions = {
  composer?: ReportComposer
  logger?: 'human' | 'json' | Logger
  stream?: {
    write(str: string): void
  }
}

export type ServerOptions = BaseServerOptions & {
  reporter?: Reporter | ReporterOptions
}
```

Now we can either pass custom reporter, or configure existing one.
In tests we can use custom reportes as before
```
let app = createServer({
    ...opts,
    reporter (name: string, details: any) {
      names.push(name)
      reports.push([name, details])
    }
})
```

Pros:
* Looks more straightforward and clean to me
Cons:
* Requires more ceremony for user to change logger, cause parameters are nested. 
    ```js
    // new way
    let reporter = createReporter({ reporter: { logger } })
    // old way
    let reporter = createReporter({ logger })
   ```
   But only from code. From console and through env variables we can pass `logger` as before.
* Doesn't remove `reporter` from API, this solution can be too "powerfull"

3. Provide some hook for reporting and remove `reporter` from API.

Don't implemented yet, (come up with this idea tonight).

Since we want to hack reporter only for tests as far as I see. Maybe we can provide just this functionality.

Will be used like
```
let app = createServer({
    ...opts,
    onReport (name: string, details: any) {
      names.push(name)
      reports.push([name, details])
    }
})
```

**Comment by ai** [comment]
I like the second way, but `createReporter({ reporter: { logger } })` is too long. The most popular way (`'json'`, custom logger) should be shorter than rare ways (reporter).

What if we will use a different signature:

```ts
type Logger = 'human' | 'json' | PinoLogger

type LoggerOptions = {
  to?: Logger,
  reporter: Reporter
  stream?: { write(str: string): void } 
}

export type ServerOptions = BaseServerOptions & {
  logger?: Logger | LoggerOptions
}
```

In this case, the most popular way to use Logux will be the same: `new Server({ logger: 'json' })` or `new Server({ logger: new GoogleCloudLogger })`, but we still can set reporter for tests: `new BaseServer({ logger: { reporter: testReporter } })`

But I am not sure about the best name for `logger.to`.

**Comment by AleksandrSl** [comment]
1. I agree with simplifying the most popular way. However we still get this problem of "confronting" `logger` (`to`) and `reporter`.
```
type Logger = 'human' | 'json' | PinoLogger

type LoggerOptions = {
  to?: Logger,
  reportComposer: ReportComposer
  stream?: { write(str: string): void } 
}

export type ServerOptions = BaseServerOptions & {
  logger?: Logger | LoggerOptions
}
```

2. Maybe `to` can be renamed to `type`

**Comment by ai** [comment]
I know! We should move `reporter` to events! `server.on('report', Reporter)`. What do you think about it?

And `logger?: Logger | LoggerOptions` is also good idea (even with moving `reporter` out of options. I do not like that we have separated `loggerStream` options.

`to` → `type` :+1:

**Comment by AleksandrSl** [comment]
Looks close to my third option, sounds good. 
So the soltuion will look something like this:

```
type Logger = 'human' | 'json' | PinoLogger

type LoggerOptions: {
  type?: Logger,
  stream?: { write(str: string): void } 
}

export type ServerOptions = BaseServerOptions & {
  logger?: Logger | LoggerOptions
}
```

and users will register reporter themselves? Or we will leave reporter in options and will register it by ourselves (sounds easier for user)?

Thus, we would have 2 reporters one internal and one specified by user that will not intefere?

We can also introduce something like `silent` logger for tests

**Comment by ai** [comment]
> and users will register reporter themselves? Or we will leave reporter in options and will register it by ourselves (sounds easier for user)?

I think we can remove reporter from options and keep only event listener API.

> We can also introduce something like silent logger for tests

By default, BaseServer and TestServer do not print anything to the log if you didn't set `logger` option.

**Comment by AleksandrSl** [comment]
Ok, I will try to implement this

**Comment by euaaaio** [comment]
Do we need to be able to pass any Pino options like `level` or `name`?

**Comment by AleksandrSl** [comment]
> Do we need to be able to pass any Pino options like `level` or `name`?

We can pass custom pino logger for now, however if it's usual case we can add these parameters to logger options

**Comment by euaaaio** [comment]
> > Do we need to be able to pass any Pino options like `level` or `name`?
> 
> We can pass custom pino logger for now, however if it's usual case we can add these parameters to logger options

It might be useful to be able to simply change any of default pino options without rewriting `logger` function.

**Comment by AleksandrSl** [comment]
Though we should be careful not to add pino specific options in case we will move from pino to some other logging library.
Configuration of custom logger is about 10 lines of code (and it's configured only once), and we definitely cannot provide the same level of configuration with options and not tie ourselves to pino. 

In the [linked discussion](https://gitter.im/logux/logux?at=5f35686a3b680170180f905d) the main point is to reduce amount of logging, maybe we could simply add option like `ignoreActions` to server if it's not already present?

@ai what do you think?

**Comment by ai** [comment]
I think it is a rare case to set `level` or `name`.

In that thread, the user should use a build-in log tool to trim unnecessary messages.

**Comment by euaaaio** [comment]
@ai yeah, mixing libraries is a bad idea. But to avoid such questions anymore, we can add a detailed example to the documentation.
