### ISSUE TITLE
Add documentation how to integrate backend-test in CI pipeline for logux backend projects.

### ISSUE THREAD

**Issue by egregors** [logux/logux#48]
Running integration tests from `backend-test` like a part of CI pipeline for every Logux backend implementation sounds pretty cool for me. In addition to checking the base functionality, it is also could be a nice indicator of support current protocol version.

So, It will be very useful to have a clear manual on how to add this step for default CI tools: TravisCI and Github Actions

**Comment by ai** [comment]
I decided to not focusing on backend integration for a while
