### ISSUE TITLE
Logux Server control server conflict with Express.js

### ISSUE THREAD

**Issue by gilrosenthal** [logux/logux#49]
Hi, I'm working with Logux as an extension of an express server with a React frontend, and everything works great in development. However, when I try working in production, it seems that the control server hijacks the serving of the react page, and just sends "Wrong path" to all clients. I commented the `bindControlServer` line out from `BaseServer.js` in my local `node_modules`, and then everything worked great. However, I recognize that that's unsustainable in a CI environment. 

I'm just wondering what the control server does? And if it would be possible to add a configuration option to the implementation of `BaseServer` that allows it to be disabled? I would be happy to make the PR if you are good with that.

**Comment by gilrosenthal** [comment]
So in my `main.js`, I have the following code: `const loguxserver = new Server(
		Server.loadOptions(process, {
			subprotocol: '1.0.0',
			supports: '1.x',
			root: __dirname,
			server: server,
		})
	)`, 
where `server` is an express server already instantiated and listening. Before I define `loguxserver`, I have a route `/api/upload`, that under normal express works perfectly. However, after adding in `loguxserver`, when I POST to `/api/upload/`, instead of doing its job it 404s and returns 'Wrong path'. When I comment out the `bindControlServer` line it works fine, however. Any idea?

**Comment by ai** [comment]
Yeap, in this case of using `server` you will have a conflict.

Do you have any reason to run Logux Server on top of Express.js. I added `server` option for rare hacks (when you need to pass specific options for HTTP server) and not everyday production usage.

**Comment by ai** [comment]
I added a note for `server` option, that Logux Server will remove all routes from the HTTP server
https://github.com/logux/server/commit/a98a0fdd807fa48bced669314fb22c82cb978ba3

**Comment by gilrosenthal** [comment]
Would you be open to a PR that allows the server to just listen to a specific subpath, i.e. `/logux`? So I could keep the express server running in the backend but also keep control running too

**Comment by ai** [comment]
Yeap. We can add `httpPath` option.

**Comment by ai** [comment]
Should be fixed in `next`. Now Logux Server listens only `UPDATE` rquest.
