### ISSUE TITLE
Add origin action to logux/undo

### ISSUE THREAD

**Issue by ai** [logux/logux#52]
```ts
{ type: 'logux/undo', action: Action, id: ID, reason: string }
```

It will simplify client’s code by avoiding looking for the origin action

- [x] Add to Logux Server
- [x] Use it in Logux Client `status`
- [x] Use it in Logux Redux time travel
- [x] Use it in Logux Vuex time travel

**Comment by clibu** [comment]
@ai Ideally server.type( 'xyz') -> access() should be able to return specific 'denied' properties.

**Comment by ai** [comment]
@euaaaio you PR to Logux Server unfortunately only half of the fix. We also will need to update Logux Client (or Logux Redux) to use `action.action` there

**Comment by euaaaio** [comment]
> @euaaaio you PR to Logux Server unfortunately only half of the fix. We also will need to update Logux Client (or Logux Redux) to use `action.action` there

Please check if the fix is correct. If so, I will make PR for others.

**Comment by euaaaio** [comment]
**Logux Client**
It seems that `status` doesn't need any updates: https://github.com/logux/client/blob/master/status/index.js#L77-L95
But I can improve the messages from `log`.

**Logux Redux / Vuex**
Here's a similar situation: https://github.com/logux/vuex/blob/master/store/index.js#L243-L247
But I can improve `LoguxUndoAction ` typings: https://github.com/logux/redux/blob/master/create-logux-creator/index.d.ts#L14-L18

**Comment by euaaaio** [comment]
Oh, there are not typings for `LoguxUndoAction` in Logux Vuex. Can we move `LoguxUndoAction ` to Logux Core like `AnyAction` and import it to Redux and Vuex?

**Comment by ai** [comment]
> But I can improve the messages from log.

Yeap, it is will be good

> Can we move LoguxUndoAction to Logux Core like AnyAction and import it to Redux and Vuex?

Let’s move it to Logux Client, since Logux Core is a core system without channels and undo logic.

**Comment by euaaaio** [comment]
@ai, you can review.
