### ISSUE TITLE
Unify Vuex and Redux API and explicitly accept client

### ISSUE THREAD

**Issue by ai** [logux/logux#53]
```js
import { CrossTabClient, createLoguxCreator } from '@logux/vuex'

let client = new CrossTabClient({ … })
let createStore = createLoguxCreator(client, { … })
let store = createStore(…)
```

Benefits:

1. Tell about important `store.client` API.
2. Ability to replace `CrossTabClient` to `Client`

**Comment by euaaaio** [comment]
@ai, maybe you mean `createStoreCreator` that returns `createStore`?

**Comment by ai** [comment]
Logux Redux is using `createLoguxCreator` name to have Logux in the function name.

Do you think we should rename the method?

**Comment by euaaaio** [comment]
I think `createStoreCreator` is more explicit then `createLoguxCreator`.

Seems like `createLoguxCreator` creates `loguxCreator` or `createLogux` function. But it should create `createStore` which is native Vuex and Redux function.

The latest Logux Vuex uses `createLogux`, that creates Logux instance:

```js
import { createLogux } from '@logux/vuex'

const Logux = createLogux({ … })
const store = new Logux.Store({ … })
```

**Comment by ai** [comment]
Yeap, we can rename the function. It also allows me to show a warning to update API.

**Comment by euaaaio** [comment]
Some questions about Redux:
1. Should the current API still be working?
2. `console.warn` would be enough for warning?

**Comment by ai** [comment]
> Should the current API still be working?

It will be nice to help with migration, but we do not have too many users right now to make a smooth migration is mandatory.

I didn’t decide yet.
