### ISSUE TITLE
Fix useDispatch types in Logux Redux

### ISSUE THREAD

**Issue by ai** [logux/logux#55]
We need to add own `useDispatch` to Logux Redux to return a correct type for TypeScript

**Comment by euaaaio** [comment]
```ts
import { Action, AnyAction } from 'redux'

import { LoguxDispatch } from '../create-logux-creator/index.js'

export function useDispatch<A extends Action = AnyAction> (): LoguxDispatch<A>
```

Maybe I can take over. Something like this?

**Comment by ai** [comment]
Yeap. But it is better to checkout the official `useDispatch` types

**Comment by euaaaio** [comment]
Original `useDispatch` returns the standard `Dispatch` type defined by the Redux core types.
Ref: https://redux.js.org/recipes/usage-with-typescript#typing-the-usedispatch-hook

My suggestion [based on DefinitelyTyped package `@types/react-redux`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3334a723a7dd2482b8ee82c0542738dd15316cc4/types/react-redux/index.d.ts#L529):
```ts
export function useDispatch<TDispatch = Dispatch<any>>(): TDispatch;
export function useDispatch<A extends Action = AnyAction>(): Dispatch<A>;
```

Am I missing something? Are there any other requirements?

**Comment by ai** [comment]
Is `Dispatch` a type of interface? If it is an interface we can extend Redux `Dispatch`.
