### ISSUE TITLE
Add unsubscribe callback to Server

### ISSUE THREAD

**Issue by ai** [logux/logux#58]
```js
server.channel('users/:id', {
  …,
  unsubscribe (ctx) {
  }
})
```

> Use case is I want to remove player from game if they close browser

**Comment by erictheswift** [comment]
Issue title: `subsubscribe` -> `unsubscribe`

Will implement it as we need this functionality.

@ai where do you think is the place for `channel`?
Should `unsubscribe()` have same 3-argument signature like `(ctx: ChannelContext, action: LoguxUnsubscribeAction, meta: ServerMeta): void` so that we can take it as 'action.channel`?

**Comment by erictheswift** [comment]
Do I understand well that in case of client disconnect, `logux/unsubscribe` actions should also be added to server log for every channel client was subscribed to?

**Comment by ai** [comment]
> Issue title: subsubscribe -> unsubscribe

Fixed

> where do you think is the place for channel?

`channel` already implemented in `BaseServer` class. We just need to new `unsubscribe option.

> Should unsubscribe() have same 3-argument signature like (ctx: ChannelContext, action: LoguxUnsubscribeAction, meta: ServerMeta): void so that we can take it as 'action.channel`?

I like the idea to keep the same semantic everywhere.

> Do I understand well that in case of client disconnect, logux/unsubscribe actions should also be added to server log for every channel client was subscribed to?

Nope. It was unsubscribed without action. But you can generate fake action for this case.

Or maybe generating `logux/unsubscibed` on the server will be nice idea.

**Comment by erictheswift** [comment]
Implemented.
I'm adding `logux/unsubscribe` on client destruction for every subscribed channel as if it was emitted by a client.

**Comment by erictheswift** [comment]
Btw what is the ETA of these changes in npm? ;)

**Comment by ai** [comment]
> Btw what is the ETA of these changes in npm? ;)

A few months. I need to add a few features to `next` and then document all changes.

It is better to move to `next` branch.
