### ISSUE TITLE
Move type to interface in d.ts files

### ISSUE THREAD

**Issue by ai** [logux/logux#76]
There are many posts than `interface` works faster than `type` in TypeScript. I think we should consider moving to `interface`.

**Comment by brodybits** [comment]
Just out of curiosity for clarification what you mean by "faster"?

**Comment by ai** [comment]
I am not very deep into this topic, but seems like TS inline `type` structure every time it is used, which leads to big memory usage. In contrast `interface` is used by link.

@11bit am I right?

**Comment by brodybits** [comment]
> seems like TS inline `type` structure every time it is used, which leads to big memory usage

Do you mean that this might happen when someone else uses a Logux dependency in a client application written in TypeScript?

I wonder if we can think of an easy way to check and compare the effect of using the `type` structure vs `interface` when transpiling some demo code. In case we can demonstrate an adverse effect of using the `type` structure, I wonder if the TypeScript team would be interested in improving the situation.

Unfortunately I am not super familiar with the Logux interfaces or code base, just found this out of interest.

**Comment by ai** [comment]
> Do you mean that this might happen when someone else uses a Logux dependency in a client application written in TypeScript?

Yeap. Using too much `type` will cause slowing down any TypeScript compiler, which sees Logux imports.

> I wonder if we can think of an easy way to check and compare the effect of using the type structure vs interface when transpiling some demo code.

I will try to compare `check-dts` performance before and after.

> I wonder if the TypeScript team would be interested in improving the situation.

It is a very old topic. For instance, https://ncjamieson.com/prefer-interfaces/

**Comment by brodybits** [comment]
> [...]
> 2\. https://twitter.com/robpalmer2/status/1319188885197422594

Here is the important comment for the sake of TypeScript performance beginners such as myself:

> Yesterday I shrank a TypeScript declaration from 700KB to 7KB by changing one line of code 🔥

I would love to understand if this means less generated `*.d.ts` code, less generated JavaScript code, or both, just asked on Twitter: https://twitter.com/brodybits/status/1328900820142862337

**Comment by 11bit** [comment]
> I would love to understand if this means less generated *.d.ts code, less generated JavaScript code, or both, just asked on Twitter: https://twitter.com/brodybits/status/1328900820142862337

Yes, it is only about the size of *.d.ts files (generated js is the same). But since the incremental watch mode of tsc works by generating d.ts files internally this might affect ts performance in watch mode too.

**Comment by 11bit** [comment]
Usually problems with performance are caused by a public function that returns some private types. For instance, imagine we have a library with the public function someFunc returning private type A:

```ts
type A<C> = A<C>[] | C;

export function someFunc<C>(a: C): A<C> {
    return a
}
```

And we use this library somewhere in client code:


```ts
import {someFunc} from './lib';
const state: { whatever: string } = { whatever: 'state' }

export const result = someFunc(state)
```


Declaration file for this code should be somethig like this:

```
export declare const result: import("./lib").A<{
    whatever: string;
}>;
```

Since the A is private type, TS can not do it. But it tries its best and generates the following beautiful construction in d.ts:

```ts
export declare const result: {
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | ({
    whatever: string;
} | any)[])[])[])[])[])[])[])[])[])[])[];
```

Depending of the size of client types and how often you use someFunc, declaration files can grow really huge. Replacing `type` with `interface` in client code can help in some situations. But in general the rule of thumb is to make sure that all the types that can be public are exported -- in the example above the fix is to add export  A (`export type A...`)
