### ISSUE TITLE
External Auth difficulties

### ISSUE THREAD

**Issue by friesendrywall** [logux/logux#80]
The way logux/vuex is written in 0.8.3+ makes external auth difficult, because the createLogux constructor takes hard coded params for token.  This really should be a callback, or allow this to dynamically retrieve a token.  Or perhaps something like 

```
store.client.start(token);
```

**Comment by ai** [comment]
In the next release of Logux Client you will be able to pass async function as a `token` argument.

https://github.com/logux/client/blob/next/client/index.d.ts#L56

You will be able to dynamically retrieve a token in that function

**Comment by ai** [comment]
You can use the next Logux Client (I recommend to wait for a release) by installing version from GitHub branch:

```
npm i @logux/client@logux/client#next
```
