### ISSUE TITLE
Lack of server's health endpoint

### ISSUE THREAD

**Issue by vitalybaev** [logux/logux#94]
It would be good to have information about server's `/health` endpoint in the docs. I've found it occasionally.
I'd rather created a pull request with such additions, but I doubt about where to place them.

**Comment by ai** [comment]
I will keep this issue open until we will have Deploy docs with block about health endpoint.

Do you want to write deploy docs?

**Comment by vitalybaev** [comment]
Yes, I try to write it. Under which section of Guides you prefer to place it?

**Comment by ai** [comment]
I thought about Recipes section.

Guide is about under standard what is Logux. Recipes are about creating a real app.
